### ISSUE TITLE
Does not work for me under plain Ubuntu 14.04.1 LTS 

### ISSUE THREAD

**Issue by phgrau** [goFrendiAsgard/kokoropy#4]
Hi,

while trying to try kokoropy, I ran in this error:

```shell
> git clone https://github.com/goFrendiAsgard/kokoropy.git
> cd kokoropy
> python -V
Python 2.7.6
> lsb_release -a    
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.1 LTS
Release:	14.04
Codename:	trusty
> python rossian.py start
Traceback (most recent call last):
  File "rossian.py", line 3, in <module>
    import subprocess, signal, time, datetime, os, sys, getopt, kokoropy
  File "/home/phgrau/src/kokoropy/kokoropy/__init__.py", line 8, in <module>
    from kokoro import *
  File "/home/phgrau/src/kokoropy/kokoropy/kokoro.py", line 34, in <module>
    from sqlalchemy import Column, Integer, String, create_engine
  File "/home/phgrau/src/kokoropy/kokoropy/packages/sqlalchemy/__init__.py", line 8, in <module>
    from .sql import (
  File "/home/phgrau/src/kokoropy/kokoropy/packages/sqlalchemy/sql/__init__.py", line 7, in <module>
    from .expression import (
  File "/home/phgrau/src/kokoropy/kokoropy/packages/sqlalchemy/sql/expression.py", line 29, in <module>
    from .visitors import Visitable
  File "/home/phgrau/src/kokoropy/kokoropy/packages/sqlalchemy/sql/visitors.py", line 27, in <module>
    from .. import util
  File "/home/phgrau/src/kokoropy/kokoropy/packages/sqlalchemy/util/__init__.py", line 43, in <module>
    from functools import _partial
ImportError: cannot import name _partial
>
```
There is no `_partial` in my `/usr/lib/python2.7/functools.py`(which is the distribution default), there is a `partial`, but changing leads to other errors...  
Not shure what to do? Update or downgrade sqlalchemy? Use an other python?
Do you have any idea?

Kind regards,

Philipp

**Comment by goFrendiAsgard** [comment]
Hi, Philipp. Thanks for your report.
I also use ubuntu 14.04, and I use sqlalchemy from ubuntu repository.
```
sudo apt-get install python-sqlalchemy
```
Therefore, I don't realize the incompatibility problem.

I try to uninstall sqlalchemy from the system to enforce kokoropy use sqlalchemy provided in the distribution, and the error occurs.

I manage to solve this by update sqlalchemy to 0.9.8, and I've just push the update.
https://github.com/goFrendiAsgard/kokoropy/commit/a9cfe3a966d5df89402d805a00739622d0439c0f

Try to download again, and it should works as expected.
Please close the issue if you find the update works.

Kind regards,

Go Frendi

**Comment by phgrau** [comment]
Thank you, it now works.
